version: '3.8'

services:
  postgres-db:
    image: pgvector/pgvector:pg16
    container_name: postgres-db
    environment:
      POSTGRES_DB: genai_idea
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: manager
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge